def display_menu():
    print("=" * 38)
    print(" EVENT EQUIPMENT RENTAL MANAGEMENT ")
    print("=" * 38)
    print("1. Add new equipment")
    print("2. Search equipment by ID")
    print("3. Search equipment by status")
    print("4. Update equipment details")
    print("5. Sort equipment")
    print("6. Group equipment by status")
    print("7. Add new rental order")
    print("8. Calculate rental fees and late penalties")
    print("9. Search rental by ID")
    print("10. Sort rental orders")
    print("11. Load equipment data")
    print("12. Save equipment data")
    print("13. Load rental data")
    print("14. Save rental data")
    print("0. Exit")
    print("=" * 38)
